version: "3"

services:
  app:
    build: .
    depends_on:
      - mongo
    ports:
      - 5000:5000
    volumes:
      - .:/app/
      - /app/node_modules

    command: yarn dev

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
