version: "3"

services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - 5000:5000
    volumes:
      - .:/app/
      - /app/node_modules

    command: yarn dev

  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
