version: "3"

services:
  app:
    build: .
    depends_on:
      - mongo
      - redis
    ports:
      - 5000:5000
    volumes:
      - .:/app/
      - /app/node_modules

    command: [sh, -c, "yarn && yarn dev"]

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
